/*
 * Created by Sujoy Datta. Copyright (c) 2020. All rights reserved.
 *
 * To the person who is reading this..
 * When you finally understand how this works, please do explain it to me too at sujoydatta26@gmail.com
 * P.S.: In case you are planning to use this without mentioning me, you will be met with mean judgemental looks and sarcastic comments.
 */

package com.morningstar.planetary.models

data class VbtyFlds(
    val _ExteriorConstruction: Boolean,
    val _ExteriorFeatures: Boolean,
    val _HOA: Boolean,
    val _IsFeaturedlisting: Boolean,
    val _MLSAreaMajor: Boolean,
    val _MajorSubdivision: Boolean,
    val _MinorSubdivision: Boolean,
    val _SeniorCommunityYN: Boolean,
    val _SpecialListingConditions: Boolean,
    val _allowable: Boolean,
    val _amenities: Boolean,
    val _appliances: Boolean,
    val _area: Boolean,
    val _basement: Boolean,
    val _bedroomDescription: Boolean,
    val _bedroomsonLowerFloor: Boolean,
    val _bedroomsonMainFloor: Boolean,
    val _bedroomsonUpperFloor: Boolean,
    val _boathouseDock: Boolean,
    val _communityExtra: Boolean,
    val _condition: Boolean,
    val _construction: Boolean,
    val _constructionStatus: Boolean,
    val _cooling: Boolean,
    val _county: Boolean,
    val _district: Boolean,
    val _exteriorType: Boolean,
    val _fireplaces: Boolean,
    val _fireplaceyn: Boolean,
    val _foreclosure: Boolean,
    val _foundation: Boolean,
    val _fullBathsonLowerFloor: Boolean,
    val _fullBathsonMainFloor: Boolean,
    val _fullBathsonUpperFloor: Boolean,
    val _garage: Boolean,
    val _garagespaces: Boolean,
    val _golfCourseFrontage: Boolean,
    val _halfBathsonLowerFloor: Boolean,
    val _halfBathsonMainFloor: Boolean,
    val _halfBathsonUpperFloor: Boolean,
    val _hasImage: Boolean,
    val _hasVirtualTour: Boolean,
    val _heating: Boolean,
    val _interior: Boolean,
    val _isFurnished: Boolean,
    val _kithchenBreakfast: Boolean,
    val _lakeName: Boolean,
    val _landstyle: Boolean,
    val _laundryLocation: Boolean,
    val _laundryType: Boolean,
    val _location: Boolean,
    val _lotDescription: Boolean,
    val _maxDaysListed: Boolean,
    val _model: Boolean,
    val _occupancy: Boolean,
    val _openhouse: Boolean,
    val _parking: Boolean,
    val _parkingspaces: Boolean,
    val _parkview: Boolean,
    val _patio: Boolean,
    val _pool: Boolean,
    val _poolDescription: Boolean,
    val _possibleFinancing: Boolean,
    val _pricereduction: Boolean,
    val _propertyDescription: Boolean,
    val _propertySetting: Boolean,
    val _rooms: Boolean,
    val _shortsale: Boolean,
    val _stories: Boolean,
    val _style: Boolean,
    val _view: Boolean,
    val _viewFeature: Boolean,
    val _waterDescription: Boolean,
    val _waterExtra: Boolean,
    val _waterFrontView: Boolean,
    val _waterSourse: Boolean,
    val _waterfront: Boolean,
    val _waterview: Boolean,
    val _yearRenovated: Boolean
)